//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_EnglishBattle.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnglishBattle2Entities : DbContext
    {
        public EnglishBattle2Entities()
            : base("name=EnglishBattle2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Joueur> Joueur { get; set; }
        public virtual DbSet<Partie> Partie { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Verbe> Verbe { get; set; }
        public virtual DbSet<Ville> Ville { get; set; }
    }
}
